baseURL = "https://mx-eternity.github.io/"
title = "Matrix Eternity Documentation"
enableGitInfo = true
theme = "book"

# Needed for mermaid/katex shortcodes
[markup]
[markup.goldmark.renderer]
  unsafe = true


[markup.tableOfContents]
  startLevel = 1

[params]
    BookRepo = 'https://github.com/mx-eternity/docs'
    BookDateFormat = '2 January, 2006'
    BookComments = false
    BookEditPath = 'edit/master'
    # TODO make collapse stuff work
    BookMenuBundle = '/menu'

[languages]
[languages.en]
  languageName = 'English'
  contentDir = 'content'
  weight = 1

[menu]
# [[menu.before]]
[[menu.after]]
  name = "Github"
  url = "https://github.com/mx-eternity/docs"
  weight = 10
